export const ActionTypes = {
    USER_SIGN_UP: "USER_SIGN_UP",
    SELECT_USER_ROLE: "SELECT_USER_ROLE",
    SET_USER_ROLE: "SET_USER_ROLE",
    SET_USER_UID: "SET_USER_UID",
    GET_DATA_FROM_ASYNCSTORAGE: "GET_DATA_FROM_ASYNCSTORAGE",
    USER_LOGOUT: "USER_LOGOUT",
}